version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  git-gud:
    cmds:
      - git add --all
  run:
    deps:
      - build
      - git-gud
    cmds:
      - nix run . --show-trace
    method: none
  debug:
    deps:
      - build-debug
    cmds:
      - gdb debug/main --tui
    aliases:
      - d
    method: none
  debug-dap:
    cmds:
      - gdb debug/main -i dap
    method: none
  build:
    deps:
      - git-gud
    cmds:
      - nix build . --show-trace
    aliases:
      - b
  build-test:
    deps:
      - git-gud
      - mkdir-debug
    cmds:
      - odin test src/main/ -out:debug/main -o:none -all-packages
      #- nix run . --show-trace
    aliases:
      - test
    method: none
  mkdir-debug:
    sources:
      - "debug/"
    cmds:
      - mkdir -p debug
    internal: true
  build-debug:
    deps:
      - mkdir-debug
    sources:
      - "src/**/*.odin"
    cmds:
      - odin build src/main -out:debug/main -o:none -debug
    aliases:
      - bd
    generates:
      - debug/main
  watch:
    watch: true
    sources:
      - "src/**/*.odin"
    cmds:
      - task: test
  watch-run:
    sources:
      - "src/**/*.odin"
    cmds:
      - task: run
