version: '3'

interval: 500ms
tasks:
  test:
    watch: true
    sources:
      - 'src/**/*.odin'
    cmds: 
      - odin test src/sudoku
  test-run:
    watch: true
    sources:
      - 'src/**/*.odin'
    cmds: 
      - odin run src/sudoku
