version: "3"
interval: 500ms
tasks:
  default:
    cmds:
      - task: env-reload
  env-reload:
    cmds:
      - direnv reload
      - nix-direnv-reload
    aliases:
      - env
  git-gud:
    cmds:
      - git add --all
  run:
    deps:
      - git-gud
    cmds:
      - nix run . --show-trace
  debug:
    deps:
      - build-debug
    cmds:
      - gdb debug/main --tui
    aliases:
      - d
  debug-dap:
    cmds:
      - gdb debug/main -i dap
  build:
    deps:
      - git-gud
    cmds:
      - nix build . --show-trace
    aliases:
      - b
  build-test:
    deps:
      - git-gud
      - mkdir-debug
    cmds:
      - eval "$TEST_CMD"
    aliases:
      - test
    env:
      src: ./src/main/
  mkdir-debug:
    cmds:
      - rm -r debug || true
      - mkdir debug
    internal: true
  build-debug:
    deps:
      - mkdir-debug
    cmds:
      - eval "$DEBUG_CMD"
    aliases:
      - bd
    env:
      src: ./src/main/
  watch:
    watch: true
    sources:
      - "src/**/*.odin"
    cmds:
      - task: test
  watch-run:
    sources:
      - "src/**/*.odin"
    cmds:
      - task: run
